global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 20
  publish_frequency: 5 
  static_map: true
  width: 40 
  height: 40 
  origin_x: -20 
  origin_y: -20 
  resolution: 0